plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.livespeech'
version = '0.1.0'

android {
  namespace "expo.modules.livespeech"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation("com.squareup.okhttp3:okhttp:4.12.0")
}
